'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar/navbar'
import { SessionProvider, signOut, useSession } from 'next-auth/react'
import { usePathname } from 'next/navigation'
import { useEffect } from 'react'
import AutoLogoutProvider from './components/autoLogoutProvider'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const disbaleNavbar = ["/auth", "/wishlist"]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <AutoLogoutProvider>
            {!disbaleNavbar.includes(pathname) && <Navbar />}
            {children}
          </AutoLogoutProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
